-- Make the bench-photos bucket private.
--
-- Emergency egress fix (Sept 2, 2026): the public bucket's permanent photo
-- URLs were being mass-downloaded by an external bot (487 GB of cached
-- egress against the 5 GB free-plan quota in ~2 days), putting the project
-- at risk of Fair Use Policy restrictions. Going private means photos are
-- only served via short-lived signed URLs generated by the get-photo-urls
-- edge function (app) and bench-og (social previews).
--
-- Uploads are unaffected: they rely on storage RLS policies, not bucket
-- visibility. New photo rows now store bare storage paths; existing rows
-- keep their legacy public URLs, which the frontend normalizes back to
-- paths before signing.

UPDATE storage.buckets SET public = false WHERE id = 'bench-photos';
